### Challenge 1 - Installing & Importing Pandas

In [98]:
import pandas as pd

### Challenge 2 - Load the dataset

In [101]:
# Load the dataset from github or local storage
df = pd.read_csv("network_traffic_data.csv")

### Challenge 3 - display the first five rows of the data

In [104]:
# display the first five rows
df.head()

,Timestamp,Source_IP,Destination_IP,Protocol,Port,Bytes_Sent,Bytes_Received,Status,Threat_Level
0,2025-03-19 13:04:10,10.0.0.15,192.168.1.20,TCP,NaN,5411,8989,Blocked,Low
1,2025-03-19 13:03:40,192.168.1.13,172.217.169.46,ICMP,443.0,4999,11808,Allowed,Medium
2,2025-03-19 13:03:10,10.0.0.5,203.0.113.99,HTTP,443.0,6360,10852,Allowed,Medium
3,2025-03-19 13:02:40,10.0.0.9,192.168.1.20,TCP,NaN,4011,14314,Blocked,Low
4,2025-03-19 13:02:10,192.168.1.4,172.217.169.46,FTP,NaN,5254,8718,Blocked,Medium

In [106]:
df.shape

(1000, 9)

In [108]:
df.columns

Index(['Timestamp', 'Source_IP', 'Destination_IP', 'Protocol', 'Port',
       'Bytes_Sent', 'Bytes_Received', 'Status', 'Threat_Level'],
      dtype='object')

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Timestamp       1000 non-null   object
 1   Source_IP       1000 non-null   object
 2   Destination_IP  1000 non-null   object
 3   Protocol        1000 non-null   object
 4   Port            874 non-null    float64
 5   Bytes_Sent      1000 non-null   int64
 6   Bytes_Received  1000 non-null   int64
 7   Status          1000 non-null   object
 8   Threat_Level    1000 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 70.4+ KB

In [112]:
df.tail()

,Timestamp,Source_IP,Destination_IP,Protocol,Port,Bytes_Sent,Bytes_Received,Status,Threat_Level
995,2025-03-19 04:46:40,10.0.0.46,172.217.169.46,DNS,53.0,2290,6246,Blocked,Low
996,2025-03-19 04:46:10,10.0.0.3,8.8.8.8,HTTP,443.0,3470,12474,Allowed,Low
997,2025-03-19 04:45:40,10.0.0.3,192.168.1.20,UDP,21.0,6655,13170,Blocked,Low
998,2025-03-19 04:45:10,192.168.1.30,172.217.169.46,DNS,NaN,7308,13117,Blocked,Low
999,2025-03-19 04:44:40,192.168.1.34,8.8.8.8,ICMP,3389.0,726,279,Allowed,Low

In [114]:
df.describe()

              Port   Bytes_Sent  Bytes_Received
count   874.000000  1000.000000     1000.000000
mean   1819.739130  5143.572000     7562.659000
std    2899.374632  2808.256143     4240.206295
min      21.000000   106.000000      102.000000
25%      22.000000  2857.000000     4025.500000
50%      80.000000  5224.000000     7584.500000
75%    3389.000000  7487.750000    11147.750000
max    8080.000000  9984.000000    14977.000000

In [116]:
selected_columns = df[["Threat_Level", "Source_IP","Destination_IP",]]

In [118]:
selected_columns

    Threat_Level     Source_IP  Destination_IP
0            Low     10.0.0.15    192.168.1.20
1         Medium  192.168.1.13  172.217.169.46
2         Medium      10.0.0.5    203.0.113.99
3            Low      10.0.0.9    192.168.1.20
4         Medium   192.168.1.4  172.217.169.46
..           ...           ...             ...
995          Low     10.0.0.46  172.217.169.46
996          Low      10.0.0.3         8.8.8.8
997          Low      10.0.0.3    192.168.1.20
998          Low  192.168.1.30  172.217.169.46
999          Low  192.168.1.34         8.8.8.8

[1000 rows x 3 columns]

In [120]:
selected_columns.head()

  Threat_Level     Source_IP  Destination_IP
0          Low     10.0.0.15    192.168.1.20
1       Medium  192.168.1.13  172.217.169.46
2       Medium      10.0.0.5    203.0.113.99
3          Low      10.0.0.9    192.168.1.20
4       Medium   192.168.1.4  172.217.169.46

In [126]:
blocked_traffic = df[df["Status"] == "Blocked"]

In [128]:
blocked_traffic

,Timestamp,Source_IP,Destination_IP,Protocol,Port,Bytes_Sent,Bytes_Received,Status,Threat_Level
0,2025-03-19 13:04:10,10.0.0.15,192.168.1.20,TCP,NaN,5411,8989,Blocked,Low
3,2025-03-19 13:02:40,10.0.0.9,192.168.1.20,TCP,NaN,4011,14314,Blocked,Low
4,2025-03-19 13:02:10,192.168.1.4,172.217.169.46,FTP,NaN,5254,8718,Blocked,Medium
9,2025-03-19 12:59:40,10.0.0.43,10.0.0.5,ICMP,3389.0,3305,6621,Blocked,Low
10,2025-03-19 12:59:10,10.0.0.33,203.0.113.99,UDP,3389.0,3700,11297,Blocked,Medium
...,...,...,...,...,...,...,...,...,...
992,2025-03-19 04:48:10,10.0.0.11,203.0.113.99,HTTP,NaN,2839,2939,Blocked,Medium
993,2025-03-19 04:47:40,192.168.1.39,192.168.1.20,ICMP,22.0,4178,8307,Blocked,Low
995,2025-03-19 04:46:40,10.0.0.46,172.217.169.46,DNS,53.0,2290,6246,Blocked,Low
997,2025-03-19 04:45:40,10.0.0.3,192.168.1.20,UDP,21.0,6655,13170,Blocked,Low
998,2025-03-19 04:45:10,192.168.1.30,172.217.169.46,DNS,NaN,7308,13117,Blocked,Low

In [132]:
blocked_summary = blocked_traffic[["Timestamp", "Source_IP", "Destination_IP","Threat_Level"]]

In [134]:
blocked_summary

               Timestamp     Source_IP  Destination_IP Threat_Level
0    2025-03-19 13:04:10     10.0.0.15    192.168.1.20          Low
3    2025-03-19 13:02:40      10.0.0.9    192.168.1.20          Low
4    2025-03-19 13:02:10   192.168.1.4  172.217.169.46       Medium
9    2025-03-19 12:59:40     10.0.0.43        10.0.0.5          Low
10   2025-03-19 12:59:10     10.0.0.33    203.0.113.99       Medium
..                   ...           ...             ...          ...
992  2025-03-19 04:48:10     10.0.0.11    203.0.113.99       Medium
993  2025-03-19 04:47:40  192.168.1.39    192.168.1.20          Low
995  2025-03-19 04:46:40     10.0.0.46  172.217.169.46          Low
997  2025-03-19 04:45:40      10.0.0.3    192.168.1.20          Low
998  2025-03-19 04:45:10  192.168.1.30  172.217.169.46          Low

[532 rows x 4 columns]